### ISSUE TITLE
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/plugins/kernel_v2/config/vm.rb:319:in `network': wrong number of arguments (given 2, expected 1) (ArgumentError)

### ISSUE THREAD

**Issue by john1726** [stemar/vagrant-ubuntu-22-04#1]
When I try to provision the guest I am getting this error:

```
psalm@Grieg MSYS /d/VirtualMachines/ubuntu-22-04
# vagrant up --provision
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/plugins/kernel_v2/config/vm.rb:319:in `network': wrong number of arguments (given 2, expected 1) (ArgumentError)
        from D:/VirtualMachines/ubuntu-22-04/Vagrantfile:20:in `block (2 levels) in <top (required)>'
        from D:/VirtualMachines/ubuntu-22-04/Vagrantfile:19:in `each'
        from D:/VirtualMachines/ubuntu-22-04/Vagrantfile:19:in `block in <top (required)>'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/config/v2/loader.rb:37:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/config/loader.rb:126:in `block (2 levels) in load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/config/loader.rb:119:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/config/loader.rb:119:in `block in load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/config/loader.rb:116:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/config/loader.rb:116:in `load'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/vagrantfile.rb:31:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/environment.rb:817:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/environment.rb:817:in `vagrantfile'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/environment.rb:998:in `process_configured_plugins'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/lib/vagrant/environment.rb:189:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/bin/vagrant:211:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.3.6/bin/vagrant:211:in `<main>'
```

Here is my settings.yml:

---
:machine:
  # https://app.vagrantup.com/bento/boxes/ubuntu-22-04
  :box: bento/ubuntu-22.04 # 64GB HDD
  :memory: 3072 # 3GB RAM
  :cpus: 1
  :hostname: ubuntu-22-04
  :timezone: Canada/Pacific

:forwarded_ports:
# SSH
- :id: ssh
  :host: 2200
  :guest: 22
# HTTP
- :host: 8000
  :guest: 80
# MySQL
- :host: 33060
  :guest: 3306

:synced_folder:
  :host: D:/VirtualMachines/ubuntu-22-04/code
  :guest: /home/vagrant/code

:copy_files:
- :source: ~/.ssh
  :destination: ~/.ssh
- :source: ~/.gitconfig
  :destination: ~/.gitconfig

:php_error_reporting: E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT
...

Do you have any suggestions?

**Comment by stemar** [comment]
Hey sorry I just saw this.
I fixed this error today.
I think it has something to do with a ruby update that restricts hashes to feed a method argument with a splat **.
I updated `Vagrantfile`
